"""initial

Revision ID: 141ad37b5e81
Revises: 
Create Date: 2022-12-11 19:49:28.764537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '141ad37b5e81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ping',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('text', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ping_id'), 'ping', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ping_id'), table_name='ping')
    op.drop_table('ping')
    # ### end Alembic commands ###
