"""added models schemas and endpoints for users

Revision ID: 4a92df23bfe3
Revises: 938c50445b8b
Create Date: 2022-12-21 16:25:32.690142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a92df23bfe3'
down_revision = '938c50445b8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
