"""add column

Revision ID: 69174a687505
Revises: 141ad37b5e81
Create Date: 2022-12-14 17:21:33.242241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69174a687505'
down_revision = '141ad37b5e81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NFT_PR',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=30), nullable=False),
    sa.Column('image_URL', sa.String(length=100), nullable=True),
    sa.Column('buy_token_name', sa.String(length=5), nullable=True),
    sa.Column('chain_name', sa.String(length=30), nullable=True),
    sa.Column('floor_price_BT', sa.DECIMAL(), nullable=True),
    sa.Column('BT_price', sa.DECIMAL(), nullable=True),
    sa.Column('earn_token_name', sa.String(length=5), nullable=True),
    sa.Column('ET_price', sa.DECIMAL(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('earn_rate_ET', sa.DECIMAL(), nullable=True),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_NFT_PR_id'), 'NFT_PR', ['id'], unique=False)
    op.drop_table('nft_pr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nft_pr',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='db for nft PR',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='db for nft PR',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_NFT_PR_id'), table_name='NFT_PR')
    op.drop_table('NFT_PR')
    # ### end Alembic commands ###
