"""changed schema and data-model

Revision ID: 938c50445b8b
Revises: e937db14910b
Create Date: 2022-12-20 16:50:55.437716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '938c50445b8b'
down_revision = 'e937db14910b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nft_pr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=30), nullable=False),
    sa.Column('image_URL', sa.String(length=100), nullable=True),
    sa.Column('buy_token_name', sa.String(length=5), nullable=True),
    sa.Column('chain_name', sa.String(length=30), nullable=True),
    sa.Column('floor_price_BT', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('earn_token_name', sa.String(length=5), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('earn_rate_ET', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nft_pr_id'), 'nft_pr', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ping',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', mysql.VARCHAR(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ping_id', 'ping', ['id'], unique=False)
    op.drop_index(op.f('ix_nft_pr_id'), table_name='nft_pr')
    op.drop_table('ping')
    # ### end Alembic commands ###
