"""pre-launch: changed models, schemas connected APIs

Revision ID: e34c464d2c98
Revises: b3e24e6bced6
Create Date: 2023-01-04 08:49:55.121760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e34c464d2c98'
down_revision = 'b3e24e6bced6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nft_pr', sa.Column('project_webpage_url', sa.String(length=100), nullable=True))
    op.add_column('nft_pr', sa.Column('nft_required_number', sa.Integer(), nullable=True))
    op.add_column('nft_pr', sa.Column('poster_url', sa.String(length=100), nullable=True))
    op.drop_column('nft_pr', 'project_site_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nft_pr', sa.Column('project_site_url', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('nft_pr', 'poster_url')
    op.drop_column('nft_pr', 'nft_required_number')
    op.drop_column('nft_pr', 'project_webpage_url')
    # ### end Alembic commands ###
