"""new db

Revision ID: e937db14910b
Revises: e5c8e843163c
Create Date: 2022-12-16 15:18:35.069363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e937db14910b'
down_revision = 'e5c8e843163c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NFT_PR',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=30), nullable=False),
    sa.Column('image_URL', sa.String(length=100), nullable=True),
    sa.Column('buy_token_name', sa.String(length=5), nullable=True),
    sa.Column('chain_name', sa.String(length=30), nullable=True),
    sa.Column('floor_price_BT', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('BT_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('earn_token_name', sa.String(length=5), nullable=True),
    sa.Column('ET_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('earn_rate_ET', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_NFT_PR_id'), 'NFT_PR', ['id'], unique=False)
    op.drop_index('ix_NFT_PR_id', table_name='nft_pr')
    op.drop_table('nft_pr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nft_pr',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('image_URL', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('buy_token_name', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('chain_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('floor_price_BT', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('BT_price', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('earn_token_name', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('ET_price', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('last_updated', mysql.DATETIME(), nullable=True),
    sa.Column('earn_rate_ET', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('contract_address', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_NFT_PR_id', 'nft_pr', ['id'], unique=False)
    op.drop_index(op.f('ix_NFT_PR_id'), table_name='NFT_PR')
    op.drop_table('NFT_PR')
    # ### end Alembic commands ###
